---
- name: manage_lvm | creating new LVM volume group(s)
  lvg:
    vg: "{{ item['vgname'] }}"
    pvs: "{{ item['disks']|join(',') }}"
    state: "present"
  become: true
  with_items: "{{ lvm_groups }}"
  when: >
        (item['create'] is defined and
        item['create'])
- name: manage_lvm | creating new LVM logical volume(s)
  lvol:
    vg: "{{ item[0]['vgname'] }}"
    lv: "{{ item[1]['lvname'] }}"
    size: "{{ item[1]['size'] }}"
    shrink: no
    opts: "{{ item[1]['opts'] | default('') }}"
    state: "present"
  become: true
  register: lvm
  with_subelements:
    - "{{ lvm_groups }}"
    - lvnames
  when: >
        ((item[0]['create'] is defined
        and item[0]['create']) and
        (item[1] is defined and
        item[1] != 'None') and
        (item[1]['create'] is defined and
        item[1]['create']))
        
- name: manage_lvm | resizing swap
  shell: "swapoff -a && lvresize -L +{{ item[1]['size'] }} /dev/{{ item[0]['vgname'] }}/{{ item[1]['lvname'] }} && mkswap /dev/{{ item[0]['vgname'] }}/{{ item[1]['lvname'] }} && swapon -va"
  become: true
  with_subelements:
    - "{{ lvm_groups }}"
    - lvnames
  when: >
        lvm['changed'] and
        item[1]['filesystem'] is defined and
        item[1]['filesystem'] == "swap"
  tags: reswap
  
