---
- hosts:  _managed_ecom_web_ecom_web
  vars:
    lvm_groups:
      - vgname: vg00
        disks:
          create: true
        lvnames:
          - lvname: swap
            size: 5g
            create: true
            filesystem: swap
            mount: true
            mntp: 
    manage_lvm: true
    pri_domain_name: 'autozone.com'
  roles:
    - role: ansible-manage-lvm
  tags: reswap
