---
- hosts:  _managed_os_lx
  vars:
    lvm_groups:
      - vgname: vg00
        disks:
          create: false
        lvnames:
          - lvname: swap
            size: 5g
            create: true
            filesystem: swap
            mount: false
            mntp: 
    manage_lvm: true
    pri_domain_name: 'autozone.com'
  roles:
    - role: ansible-manage-lvm
      tags: reswap
